Repository 8-do-nenemddin/DECASE-BE, pull requests merged in 2025-06, with the labels that each got.

#15 Feat/user : 회원 관련 로직 개발
  .gitignore
  README.md
  build.gradle
  src/main/java/com/skala/decase/domain/member/controller/AuthController.java
  src/main/java/com/skala/decase/domain/member/controller/MemberController.java
  src/main/java/com/skala/decase/domain/member/controller/dto/request/DeleteRequest.java
  src/main/java/com/skala/decase/domain/member/controller/dto/request/DuplicationCheckRequest.java
  src/main/java/com/skala/decase/domain/member/controller/dto/response/DeleteResponse.java
  src/main/java/com/skala/decase/domain/member/controller/dto/response/DuplicationCheckResponse.java
  src/main/java/com/skala/decase/domain/member/mapper/CheckDuplicationMapper.java
  src/main/java/com/skala/decase/domain/member/mapper/DeleteMapper.java
  src/main/java/com/skala/decase/domain/member/service/AuthService.java
  src/main/java/com/skala/decase/domain/member/service/MemberService.java
  src/main/resources/application.yml
Labels: 🔥 feat

#22 feat : 요구사항 수정/삭제 로직 생성
  src/main/java/com/skala/decase/domain/requirement/controller/RequirementController.java
  src/main/java/com/skala/decase/domain/requirement/controller/dto/CreateRequirementDto.java
  src/main/java/com/skala/decase/domain/requirement/controller/dto/UpdateRequirementDto.java
  src/main/java/com/skala/decase/domain/requirement/domain/Requirement.java
  src/main/java/com/skala/decase/domain/requirement/domain/RequirementDocument.java
  src/main/java/com/skala/decase/domain/requirement/exception/RequirementException.java
  src/main/java/com/skala/decase/domain/requirement/repository/RequirementDocumentRepository.java
  src/main/java/com/skala/decase/domain/requirement/service/RequirementService.java
Labels: 🔥 feat

#23 Feat: 프로젝트 회원 초대 관련 로직 구현
  build.gradle
  src/main/java/com/skala/decase/domain/member/repository/MemberProjectRepository.java
  src/main/java/com/skala/decase/domain/member/repository/MemberRepository.java
  src/main/java/com/skala/decase/domain/member/service/MemberService.java
  src/main/java/com/skala/decase/domain/project/controller/ProjectMemberController.java
  src/main/java/com/skala/decase/domain/project/controller/dto/request/ChangeStatusRequest.java
  src/main/java/com/skala/decase/domain/project/controller/dto/request/CreateMemberProjectRequest.java
  src/main/java/com/skala/decase/domain/project/controller/dto/response/CreateMemberProjectResponse.java
  src/main/java/com/skala/decase/domain/project/controller/dto/response/DeleteMemberResponse.java
  src/main/java/com/skala/decase/domain/project/controller/dto/response/JoinProjectResponse.java
  src/main/java/com/skala/decase/domain/project/controller/dto/response/MemberProjectResponse.java
  src/main/java/com/skala/decase/domain/project/domain/MemberProject.java
  src/main/java/com/skala/decase/domain/project/domain/Permission.java
  src/main/java/com/skala/decase/domain/project/domain/ProjectInvitation.java
  src/main/java/com/skala/decase/domain/project/mapper/ProjectMemberMapper.java
  src/main/java/com/skala/decase/domain/project/mapper/SuccessMapper.java
  src/main/java/com/skala/decase/domain/project/repository/ProjectInvitationRepository.java
  src/main/java/com/skala/decase/domain/project/service/MailService.java
  src/main/java/com/skala/decase/domain/project/service/ProjectInvitationService.java
  src/main/resources/application-local.yml
Labels: 🔥 feat

#33 Feat/memberProjectInvitation: 프로젝트 초대 현황 목록 조회 기능 구현
  src/main/java/com/skala/decase/domain/project/controller/ProjectMemberController.java
  src/main/java/com/skala/decase/domain/project/controller/dto/response/MemberInvitationResponse.java
  src/main/java/com/skala/decase/domain/project/mapper/ProjectMemberMapper.java
  src/main/java/com/skala/decase/domain/project/repository/ProjectInvitationRepository.java
  src/main/java/com/skala/decase/domain/project/service/ProjectInvitationService.java
Labels: 🔥 feat

#32 feat: 단일 프로젝트 조회 api 추가
  src/main/java/com/skala/decase/domain/project/controller/ProjectController.java
  src/main/java/com/skala/decase/domain/project/controller/dto/response/ProjectDetailResponseDto.java
  src/main/java/com/skala/decase/domain/project/service/ProjectService.java
Labels: 🔥 feat

#37 feat: 조견표 생성
  build.gradle
  src/main/java/com/skala/decase/domain/project/controller/ProjectController.java
  src/main/java/com/skala/decase/domain/project/controller/dto/response/MappingTableResponseDto.java
  src/main/java/com/skala/decase/domain/project/service/ProjectService.java
Labels: 🔥 feat

#43 Feat/withdraw : 회원탈퇴 api 수정
  .env.properties
  gradlew
  src/main/java/com/skala/decase/domain/member/controller/AuthController.java
  src/main/java/com/skala/decase/domain/member/service/AuthService.java
Labels: 🔥 feat

#52 fix: 메일 연속 전송 가능 하도록 수정
  build.gradle
  src/main/java/com/skala/decase/DecaseApplication.java
  src/main/java/com/skala/decase/domain/project/service/MailService.java
Labels: ♻️ refactor

#54 목업 존재 확인 api 수정
  src/main/java/com/skala/decase/domain/mockup/controller/MockupController.java
  src/main/java/com/skala/decase/domain/mockup/domain/dto/MockupExistDto.java
  src/main/java/com/skala/decase/domain/mockup/service/MockupService.java
Labels: 🔥 feat

#62 feat : 요구사항 수정 요청 api 수정
  src/main/java/com/skala/decase/domain/requirement/domain/PendingRequirement.java
  src/main/java/com/skala/decase/domain/requirement/service/PendingRequirementService.java
  src/main/java/com/skala/decase/domain/requirement/service/RequirementService.java
Labels: 🔥 feat

#63 chore : 사용자 문서 업로드 시 프로젝트 리비전 증가
  src/main/java/com/skala/decase/domain/document/service/DocumentService.java
Labels: ⚙️ chore

#66 feat : 개별 요구사항 삭제 로직 추가
  src/main/java/com/skala/decase/domain/member/domain/Member.java
  src/main/java/com/skala/decase/domain/member/repository/MemberProjectRepository.java
  src/main/java/com/skala/decase/domain/member/service/AuthService.java
  src/main/java/com/skala/decase/domain/requirement/controller/RequirementController.java
  src/main/java/com/skala/decase/domain/requirement/controller/dto/request/DeleteRequestDto.java
  src/main/java/com/skala/decase/domain/requirement/controller/dto/response/RequirementDto.java
  src/main/java/com/skala/decase/domain/requirement/domain/PendingRequirement.java
  src/main/java/com/skala/decase/domain/requirement/domain/Requirement.java
  src/main/java/com/skala/decase/domain/requirement/service/PendingRequirementService.java
  src/main/java/com/skala/decase/domain/requirement/service/RequirementService.java
  src/main/java/com/skala/decase/global/config/CorsConfig.java
Labels: 🔥 feat

#75 Chore: docs api 수정
  src/main/java/com/skala/decase/domain/document/mapper/DocumentMapper.java
  src/main/java/com/skala/decase/domain/document/service/DocumentPreviewService.java
  src/main/java/com/skala/decase/domain/document/service/DocumentService.java
Labels: ⚙️ chore
